swagger: "2.0"
info:
  description: "这是一个接口在线测试服务"
  version: "1.0.0"
  title: "接口文档"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html12;3"
host: "localhost:3000"
basePath: "/api"
tags:
- name: "user"
  description: "所有用户相关的接口集合"
  externalDocs:
    description: "统一各平台用户数据格式"
    url: "http://localhost:3000/"
- name: "mobile"
  description: "所有移动端相关的接口集合"
schemes:
- "https"
- "http"
paths:
  /getUserInfo:
    get:
      tags:
      - "user"
      summary: "获取用户信息"
      consumes:
      - "application/json"
      - "application/x-www-form-urlencoded"
      produces:
      - application/json
      parameters:
      - name: userId
        in: body
        description: 用户ID
        required: true
        schema:
          properties:
            userId:
              type: string
      responses:
        404:
          description: "未找到用户"
  /updateUserInfo:
    post:
      tags:
      - user
      summary: 更新用户基本信息
      consumes:
      - "application/json"
      - "application/x-www-form-urlencoded"
      produces:
      - application/json
      parameters:
      - in: body
        name: user
        description: 用户信息
        required: true
        schema:
          $ref: "#/definitions/user"
      responses:
        404:
          description: "未找到用户"
  /deleteUser:
    delete:
      tags:
      - user
      summary: 删除用户
      consumes:
      - "application/json"
      - "application/x-www-form-urlencoded"
      produces:
      - application/json
      parameters:
      - in: body
        name: userId
        description: 用户Id
        required: true
        schema:
          properties:
            userId:
              type: string
      responses:
        404:
          description: 未找到用户
definitions:
  user:
    type: "object"
    properties:
      id:
        type: "string"
      username:
        type: "string"
      firstName:
        type: "string"
      lastName:
        type: "string"
      email:
        type: "string"
      password:
        type: "string"
      phone:
        type: "string"
      userStatus:
        type: "string"
        description: "User Status"
      